# Generated by Django 4.1.3 on 2024-05-24 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique coupon ID')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, verbose_name='Valid to')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Subcategory of products where will be discount')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
