# Generated by Django 4.1.3 on 2024-05-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Product name')),
                ('characteristics', models.TextField(blank=True, verbose_name='Characteristics of product')),
                ('info', models.TextField(blank=True, verbose_name='Information about product')),
                ('img', models.ImageField(blank=True, upload_to='products_images/', verbose_name='Photo of product')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('discount_availability', models.BooleanField(default=False, verbose_name='Discount availability')),
                ('discount', models.IntegerField(blank=True, default=1, verbose_name='Discount')),
                ('price_with_discount', models.IntegerField(blank=True, default=0, verbose_name='Product price with discount')),
                ('article', models.CharField(blank=True, max_length=250, verbose_name='Product article')),
                ('status', models.CharField(choices=[('Have in shop', 'In stock'), ('Ends in shop', 'Ends in shop'), ('Not in shop', 'Out of stock')], default='Have in shop', max_length=300, verbose_name='Availability status of product')),
                ('slug', models.SlugField(blank=True, verbose_name='Product name in url')),
                ('total_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Total rating of product')),
                ('editing', models.BooleanField(default=False, verbose_name='Dont touch this field, after saving it will be True.')),
                ('price_in_usd', models.IntegerField(default=0, verbose_name='Product price in dollars')),
                ('price_in_usd_with_discount', models.IntegerField(default=0, verbose_name='Product price in dollars with discount')),
                ('bonuses', models.IntegerField(default=0, verbose_name='Bonuses for buying this product')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Category name in header of page')),
                ('name', models.CharField(max_length=150, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True, verbose_name='Category name in url')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Products categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductColorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_in_admin_panel', models.CharField(blank=True, max_length=350, verbose_name='Product color in admin panel')),
                ('color', models.CharField(max_length=350, verbose_name='Product color')),
                ('color_hex', models.CharField(blank=True, max_length=350, verbose_name='Product HEX color')),
            ],
            options={
                'verbose_name': 'Color category',
                'verbose_name_plural': 'Color categories',
            },
        ),
        migrations.CreateModel(
            name='ProductMemoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_size', models.CharField(blank=True, max_length=250, verbose_name='Size of memory')),
                ('int_memory_value', models.IntegerField(blank=True, verbose_name='Value of memory size(In megabytes)')),
            ],
            options={
                'verbose_name': 'Product memory category',
                'verbose_name_plural': 'Product memory categories',
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Subcategory name in header of page')),
                ('name', models.CharField(max_length=150, verbose_name='Subcategory name')),
                ('slug', models.SlugField(unique=True, verbose_name='Subcategory name in url')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'Products subcategories',
            },
        ),
        migrations.CreateModel(
            name='ProductVersionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Product version')),
            ],
            options={
                'verbose_name': 'Product version category',
                'verbose_name_plural': 'Product versions categories',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('review', models.TextField(verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='Products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVersionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=300, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productcolorcategory', verbose_name='Color')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productmemorycategory', verbose_name='Memory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_product', to='Products.product', verbose_name='Product')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Product subcategory')),
            ],
            options={
                'verbose_name': 'version choice',
                'verbose_name_plural': 'Versions choices',
            },
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='product_photos/%Y-%m-%d', verbose_name='Photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'Products photos',
            },
        ),
        migrations.CreateModel(
            name='ProductMemoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(blank=True, max_length=250, verbose_name='Memory at the choice button')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productcolorcategory', verbose_name='Product color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_product', to='Products.product', verbose_name='Product')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Subcategory')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productversioncategory', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'memory choice',
                'verbose_name_plural': 'Memory choices',
            },
        ),
        migrations.CreateModel(
            name='ProductColorChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250, verbose_name='Color name at the choice button')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('background_color', models.CharField(blank=True, max_length=250, verbose_name='Button background color')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productmemorycategory', verbose_name='Product memory size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.product', verbose_name='Product')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Subcategory')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productversioncategory', verbose_name='Product esim or global')),
            ],
            options={
                'verbose_name': 'Color choice',
                'verbose_name_plural': 'Colors choices',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='subcategory',
            field=models.ManyToManyField(blank=True, db_index=True, to='Products.productsubcategory', verbose_name='Subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.productcategory', verbose_name='Main category of product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.productcolorcategory', verbose_name='Product color'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.productmemorycategory', verbose_name='Product memory size'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.productversioncategory', verbose_name='Product esim or global'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.productsubcategory', verbose_name='Subcategory of product'),
        ),
    ]
