# Generated by Django 4.1.3 on 2024-05-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_version',
        ),
        migrations.DeleteModel(
            name='ProductVersionChoice',
        ),
    ]
