# Generated by Django 4.1.3 on 2024-05-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('last_name', models.CharField(max_length=300, verbose_name='Last name')),
                ('surname', models.CharField(blank=True, max_length=300, verbose_name='Surname')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Order creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Order update date')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('post_office', models.CharField(blank=True, max_length=200, verbose_name='Post office')),
                ('country', models.CharField(blank=True, max_length=250, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='City or town')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('order_total_price', models.IntegerField(default=0, verbose_name='Order total price')),
                ('order_total_price_usd', models.IntegerField(default=0, verbose_name='Order total price in USD')),
                ('use_bonuses', models.BooleanField(default=False, verbose_name='Use bonuses?')),
                ('order_status', models.IntegerField(choices=[(1, 'Completed'), (2, 'In progress')], default=2, verbose_name='Order status')),
                ('order_bonuses', models.IntegerField(default=0, verbose_name='Order bonuses')),
                ('order_bonuses_usd', models.IntegerField(default=0, verbose_name='Order bonuses in usd')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coupons.coupons', verbose_name='Coupon')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Price per item in dollars')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity of product')),
                ('item_total_price', models.IntegerField(default=0, verbose_name='Total price of item')),
                ('item_total_price_usd', models.IntegerField(default=0, verbose_name='Total price of item in usd')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Products.product', verbose_name='Product')),
            ],
        ),
    ]
