# Generated by Django 4.1.3 on 2024-05-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=550, verbose_name='Title')),
                ('text', models.TextField(blank=True, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us info',
            },
        ),
        migrations.CreateModel(
            name='RecommendedProductsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='recommended_products/photos/', verbose_name='photo')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Recommended products photo',
                'verbose_name_plural': 'Recommended products photos',
            },
        ),
    ]
